### ISSUE TITLE
Show all errors

### ISSUE THREAD

**Issue by juliuscc** [arb/celebrate#123] opened 2019-07-30 13:46 UTC
- `node` version - 10.16.0
- `celebrate` version - 10.0.1
- `joi` version (via `npm ls --depth=0 | grep joi`) - @hapi/joi@15.1.0

My `joi` schema looks like this:

```js
{
  body: {
    state: joi.object().keys({
      token_url: joi.string().required(),
      grant_type: joi.string().required(),
      user_id: joi.string().required(),
      stream_id: joi.string().required(),
      node_id: joi.string().required()
    }).required(),
    code: joi.string().required()
  }
}
```

Here is an example value that is not working as expected:

```
{ state: { token_url: 'http://test.com/oauth2/token' }, code: 'authorization_code' }
```

The issue I am having with `celebrate` is:

I am migrating from `express-validation` with `joi@14` to `celebrate` with `@hapi/joi@15.1.0`. Everything except for one thing is going smoothly.

I try to output an error in the format:
```js
[
  { field: 'state', message: '"grant_type" is required' },
  { field: 'state', message: '"user_id" is required' },
  { field: 'state', message: '"stream_id" is required' },
  { field: 'state', message: '"node_id" is required' }
]
```

I attach a custom error handler to the router and parse the incoming error. In `express-validation` you get an error array with all necessary information. With celebrate I only get one single error. It looks like this:

```js
{
  "joi": {
    "isJoi": true,
    "name": "ValidationError",
    "details": [
      {
        "message": "\"state\" is required",
        "path": ["state"],
        "type": "any.required",
        "context": { "key": "state", "label": "state" }
      }
    ],
    "_object": { "code": "authorization_code" }
  },
  "meta": { "source": "body" }
}
```

Is it possible to get all errors or do you only get one?

**Comment by Marsup** [comment] 2019-07-30 13:53
That's likely a duplicate of #67.

**Comment by juliuscc** [comment] 2019-07-30 14:03
Yes thank you!

**Closed** 2019-07-30 14:13 UTC
